In [1]:
%cd ..

/home/yujin109/airfoil-completion


/home/yujin109/airfoil-completion/.venv/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [2]:
from xfoil import XFoil

In [3]:
xf = XFoil()

In [2]:
import numpy as np
import torch

In [6]:
c_mask = torch.Tensor([[33,33,33],[44,44,44]])
c_mask

tensor([[33., 33., 33.],
        [44., 44., 44.]])

In [ ]:
uncond_mask = torch.zeros(c_mask.size(0), dtype=torch.bool)
uncond_mask

tensor([False, False])

In [16]:
p_uncond = 0.5
mask = torch.rand(c_mask.size(0)) < p_uncond
mask

tensor([ True, False])

In [18]:
c_mask * uncond_mask.unsqueeze(1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
c_mask * mask.unsqueeze(1)

tensor([[33., 33., 33.],
        [ 0.,  0.,  0.]])